<a href="https://colab.research.google.com/github/TbilKitty/East-Potomac-Park-Tracker/blob/main/Group_project_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Libraries
import pandas as pd
import os
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

In [ ]:
#Pandas can get files from URLS

file_url = "https://docs.google.com/spreadsheets/d/1TUx0iPL8N7vFpbp2CktsY-6RaZEgZq3dl-leMr_EBrw/export?format=xlsx"

#Read
my_df = pd.read_excel(file_url)

#Echo
my_df

,County,Date,Pt (1-90),Pt (91+),PT (total),Total Jail Population,Percent pt of total
0,Allegany,2014-01-01,52,29,81,152,0.532895
1,Allegany,2014-02-01,39,23,62,118,0.525424
2,Allegany,2014-03-01,39,22,61,102,0.598039
3,Allegany,2014-04-01,46,27,73,103,0.708738
4,Allegany,2014-05-01,40,19,59,88,0.670455
...,...,...,...,...,...,...,...
3547,Worcester,2025-12-01,46,18,64,104,0.615385
3548,Worcester,2026-01-01,47,16,63,114,0.552632
3549,Worcester,2026-02-01,37,12,49,98,0.500000
3550,Worcester,2026-03-01,38,19,57,102,0.558824
3551,Worcester,2026-04-01,49,9,58,100,0.580000

In [ ]:
#Pandas can get files from URLS

file_url = "https://docs.google.com/spreadsheets/d/1XvdSNWioIp5D5nxP5GodjwF4hJ7FawlS/export?format=xlsx"


#Read
my_df = pd.read_excel(file_url)

#Echo
my_df

,County,Date,Pt (1-90),Pt (91+),PT (total),Average Total County Pretrial Jail population by Year,Total Jail Population,Average Total Population Per Year by County,Average MD total Jail population by year,Percent Pretrial of Total,Average Percentage Pretrial Jail Population Per Year by County
0,Anne Arundel,2014-01-01,313,114,427,NaN,773,NaN,NaN,0.5524,NaN
1,Anne Arundel,2014-02-01,272,111,383,NaN,706,NaN,NaN,0.5425,NaN
2,Anne Arundel,2014-03-01,279,131,410,NaN,728,NaN,NaN,0.5632,NaN
3,Anne Arundel,2014-04-01,297,123,420,NaN,750,NaN,NaN,0.5600,NaN
4,Anne Arundel,2014-05-01,292,133,425,NaN,790,NaN,NaN,0.5380,NaN
...,...,...,...,...,...,...,...,...,...,...,...
883,Prince George's,2025-12-01,811,634,1445,1192.25,1544,1283.166667,23173.666667,0.9359,0.927675
884,Prince George's,2026-01-01,785,622,1407,NaN,1496,NaN,NaN,0.9405,NaN
885,Prince George's,2026-02-01,794,630,1424,NaN,1529,NaN,NaN,0.9313,NaN
886,Prince George's,2026-03-01,913,640,1553,NaN,1662,NaN,NaN,0.9344,NaN
887,Prince George's,2026-04-01,487,369,856,1310.00,959,1411.500000,23084.000000,0.8926,0.924700

In [ ]:
file_url = "https://docs.google.com/spreadsheets/d/1KKGYn0kp4yS_ucUnVAyFKP3hYf1odzq2/export?format=xlsx"


#Read
my_df = pd.read_excel(file_url)

#Echo
my_df

,Year,MD State Average,Baltimore City,Prince George's,Baltimore,Montgomery,Anne Arundel,Frederick
0,2014,10502.17,2715.58,906.75,744.75,414.50,399.25,346.17
1,2015,9292.25,2120.33,833.58,652.75,427.83,406.75,245.67
2,2016,9094.67,1901.08,843.25,657.08,437.25,427.83,257.67
3,2017,9070.42,1936.42,840.42,691.00,463.33,444.25,224.92
4,2018,8811.00,2000.92,796.75,737.00,505.33,426.83,214.25
5,2019,8241.58,1818.50,709.33,800.33,524.75,422.17,216.00
6,2020,7088.17,1809.92,634.17,697.00,516.42,348.92,175.50
7,2021,7697.17,2083.42,751.17,779.92,594.58,362.50,176.17
8,2022,8026.00,1934.33,881.58,832.25,722.08,346.75,195.00
9,2023,8132.42,1905.17,811.50,831.50,827.17,378.17,201.00
10,2024,8371.92,1877.00,866.17,756.83,942.42,409.17,199.83
11,2025,8409.75,1716.08,1192.25,696.00,926.83,399.17,220.50
12,2026,8292.75,1572.00,1310.00,696.25,868.00,398.75,219.50

In [ ]:
import pandas as pd

file_url = "https://docs.google.com/spreadsheets/d/1vvI13aBl2MlpudhnYEvZAzGvIS7jigZP/export?format=xlsx"


#Read
my_df = pd.read_excel(file_url)

#Echo
my_df

,MD State Average,Anne Arundel,Baltimore,Baltimore City,Frederick,Montgomery,Prince George's
0,10502.17,399.25,744.75,2715.58,346.17,414.50,906.75
1,9292.25,406.75,652.75,2120.33,245.67,427.83,833.58
2,9094.67,427.83,657.08,1901.08,257.67,437.25,843.25
3,9070.42,444.25,691.00,1936.42,224.92,463.33,840.42
4,8811.00,426.83,737.00,2000.92,214.25,505.33,796.75
5,8241.58,422.17,800.33,1818.50,216.00,524.75,709.33